id: P654B2C30
initial_creation_type: ocr
source_metadata:
  volumes:
    3cf38c7cf7394ffda201123795c006e0:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: དབུ་མ་འཁྲུལ་པ་འཇོམས་པ།
      total_pages: 1605
      volume_number: 57
