id: DE01DA5E0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:00:23+00:00'
last_modified: '2022-05-27T06:07:24.341136+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c4aa:
      image_group_id: I1PD95902
      title: དབུ་མ་འཁྲུལ་པ་འཇོམས་པ།
      total_pages: 1605
      order: 57
      base_file: c4aa.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
